import type { Metadata } from "next";
// "use client";
import React, { useState } from 'react';
////binaryhoriontal115.woff2  hex115.woff2 binaryvertical115.woff2
import { hingl115_font } from '@/components/lifonts/lifonts';
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import QueryProvider from "@/components/query-provider";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={ `${hingl115_font.className} antialiased` }>
				<QueryProvider>
					<ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange >
						<main className="max-w-6xl min-h-screen mx-auto py-10 space-y-10 px-5 xl:px-0">
							<Navbar />
							{children}
						</main>
					</ThemeProvider>
				</QueryProvider>
			</body>
		</html>
	);
}
